lxcfs.c

Read IO statistics from blkio subsystem for /proc/diskstats in container.
in_flight field is not used by iostats, so ignore it.
I am still not sure how to get time_in_queue from blkio subsystem, so set time_in_queue to zero.
More details see [here](https://www.kernel.org/doc/Documentation/iostats.txt)
Signed-off-by: Ye Yin <eyniy@qq.com>

Add /proc/diskstats

---

Makefile.am
lxcfs.c
tests/test-read.c
tests/test_read_proc.sh

cache for proc file. Another PR [#18](https://github.com/lxc/lxcfs/pull/18).

cache for proc file

---

lxcfs.c

Closes #33 
The code for these (a shortcut version of the other proc_*_read ones) was
doing snprintf(buf, size, ...).  If the user only requests one byte, we
just served them a trailing 0.  Fix that.
We weren't handling reads with offset in these cases either.  Fix that.

fix corner cases in uptime and diskstat read

---

README.md

- fix the paths for the files and config
- include lxc.mount.auto = cgroup:mixed

update README about the hooks configuration needed

---

lxcfs.c
pam/pam_cgfs.c

A handful of non-critical fixes found when reviewing the code.

Random fixes

---

bindings.c

There's no place where we rely on it, and it gets out of whack
if cgroups have been unmounted+remounted.
This is an alternative to https://github.com/lxc/lxcfs/pull/70.
Thanks to smemsh for the report and proposed fix.

Don't tie entries in 'hierarchies' to their subsystem id

---

bindings.c
lxcfs.c
tests/main.sh
tests/test_reload.sh

Add a pidfile so that lxcfs.postinst can easily find the right lxcfs and send a SIGUSR1 to ask it to restart.

2016 02 03/pidfile

---

Makefile.am
lxcfs.c
tests/test_reload.sh

Put the liblxcfs.so library under $LIBDIR.

2016 02 08/privlib

---

tests/Makefile.am

to get it into the make dist tarball

add test_reload.sh to extra_dist

---

pam/pam_cgfs.c

Don't always ignore it.
Do ignore it (like all others) if not listed in the -c argument.
If the logged in task's name=systemd cgroup != that of the init
task's, assume we are in systemd and rename the user's.
If they are the same, assume we are in upstart or sysvinit and
create=chown a name=systemd cgroup just as for the others.
This should fix
https://bugs.launchpad.net/ubuntu/+source/lxcfs/+bug/1543353
and allow the ubuntu systemd package to drop its cgroup related
delta.

pam_cgfs: change handling of name=systemd

---

pam/pam_cgfs.c

If current systemd cgroup does not end in user-$uid.slice/session-c%d.scope,
then pam did not create our current systemd cgroup for us, so create a new
one rather than chowning the current one.
This happens with noninteractive sessions.

pam_cgfs: create a new systemd cgroup if current isn't ours

---

pam/pam_cgfs.c

In 14.04 our pam_systemd module used a different format for the
login cgroups.  If we find one of those in our name, then we want
to just chown it to us and not do anything more, just as we do in
xenial.

pam: support 14.04

---

share/lxc.mount.hook.in

Fix lxcfs mount handling with newer lxc

---

configure.ac
lxcfs.c

Address several raised issues - thanks Markus.

Address feedback from Markus Elfring

---

bindings.c
bindings.h
lxcfs.c

implement access(2)

---

share/lxc.mount.hook.in

hook: Fix typo in previous fix

---

bindings.c

The worst remaining offending line appears to be VmallocTotal.
Suggestions for how to calculate that would be appreciated.
Closes #119
Signed-off-by: Serge Hallyn <serge@hallyn.com>

Virtualize more of the meminfo fields

---

bindings.c

- replace multiple DEBUG ifdefines with a single ifdefine at the top
- ifdefine lxcfs_debug() macro function that expands to nothing when -DDEBUG is
not given

bindings: improve debugging

---

bindings.c

bindings: use openat fd for fstatat(), unlinkat()

---

bindings.c
lxcfs.c

2016 08 21/bugfixes

---

Makefile.am
bindings.c
bindings.h
lxcfs.c

2016 08 29/libtool module

---

bindings.h

bindings: fix debug macro

---

bindings.c

bindings: restore original working directory

---

Makefile.am

autotools: add -avoid-version

---

pam/pam_cgfs.c

This is mostly equivalent to https://github.com/lxc/lxc/pull/1309.

cgfsng improve isolcpus handling

---

bindings.c

the memory limit was already correctly set by looking at the
whole cgroup hierarchy and using the minimum value, refactor
that code to support arbitrary files in the memory cgroup
and reuse it for the memsw limit as well.
Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>

fix swap values with nested cgroups

---

pam/pam_cgfs.c

Remove unused variable

---

bindings.c

cleanup: return false instead of NULL as bool

---

pam/pam_cgfs.c

pam_cgfs: make trim() safer

---

bindings.c

bindings: add mountpoint for unified hierarchy

---

bindings.c

bindings: calculate uptime via proc/<pid>/stat

---

lxcfs.c

add a switch "-d" to lxcfs. its useful when debugging libfuse.
Signed-off-by: Daniel Kang <kangliang424@gmail.com>

enable debug option

---

lxcfs.c

There is definition for libdir in configure.ac.
`AS_AC_EXPAND(LIBDIR, "$libdir")`
so we could use LIBDIR in our code.
Signed-off-by: Daniel Kang <kangliang424@gmail.com>

add common fallback dlopen for liblxcfs.so

---

pam/pam_cgfs.c

In order to not require a user to manually list all cgroup controllers
in their PAM configuration, add an "all" option that effectively just
sets all controllers as read-write.
Signed-off-by: Aleksa Sarai <asarai@suse.de>

pam_cgfs: add an 'all' option for -c

---

tests/test_proc

Fix test_proc on s390x

---

lxcfs.c

Signed-off-by: Geaaru <geaaru@gmail.com>

Add support to nonempty option

---

bindings.c

In `proc_loadavg_read()`, `cg` is allocated by`get_pid_cgroup()`, but it's not freed before returning.

bindings: fix memory leak in proc_loadavg_read()

---

bindings.c

As it is, CPU usage stats in `/proc/stat` are shared with the host and all containers (issue #180). I'm trying to find a way for each container to see only its own CPU usage.
With this patch, `proc_stat_read()` reads per-container CPU usage from the *cpuacct* cgroup, `cpuacct.usage_all` to be exact. However, this file contains only usage in `user` and `system` modes, other fields from `/proc/stat` are not present. Idle time can be calculated, but as for other values like `nice` or `iowait`, they're all reported as zeroes in the resulting `/proc/stat` file. I don't think this can be solved without the kernel providing more information.
*cpuacct* cgroup v1 has to be present, otherwise `proc_stat_read()` will return an error. This could be changed if needed, I don't know if LXCFS is supposed …

Per-container CPU usage in /proc/stat

---

config/init/systemd/lxcfs.service
config/init/sysvinit/lxcfs

To to close down https://github.com/lxc/lxcfs/pull/188
Signed-off-by: tomponline <tomp@tomp.uk>

config: Adds reload mode to sysvinit and systemd scripts.

---

Makefile.am
bindings.c
lxcfs.c
memory_utils.h

lxcfs: coding style update

---

bindings.c

I don't know for what reason anyone but care but I guess ok.
Closes #292.

bindings: enable higher precision uptime

---

README.md
lxcfs.c

Add building method to README  and enhance version option

Improve version reporting

---

bindings.c
cgroups/cgfsng.c
cgroups/cgroup.h

cgroups: add getter instead of open-coded cgfs_get_value()

---

bindings.c
cgroups/cgfsng.c
cgroups/cgroup.h

bindings: port memory to new cgroup getters and support cgroup2

---

bindings.c
bindings.h
cgroups/cgfsng.c
cgroups/cgroup.h
sysfs_fuse.c

bindings: port cpuview to new cgroup getters & cleanup macro expansion

---

bindings.c
cgroups/cgfsng.c
cgroups/cgroup.c
cgroups/cgroup.h

cgroups: fixes and improvements

---

Makefile.am
bindings.c
cgroup_fuse.c
lxcfs.c
macro.h
proc_cpuview.c
proc_cpuview.h
proc_fuse.c
proc_loadavg.c
proc_loadavg.h
utils.c
utils.h

tree-wide: post-restructuring cleanup

---

bindings.c
cgroups/cgroup.c
configure.ac
lxcfs.c
m4/ax_check_compile_flag.m4
m4/ax_check_link_flag.m4
m4/ax_pthread.m4
proc_cpuview.c
utils.c

bindings: initialize safely & compiler-based hardening

---

bindings.c
cgroups/cgroup_utils.c
configure.ac
lxcfs.c
proc_fuse.c
utils.c
utils.h

bindings: cleanup various parts

---

Makefile.am
cgroups/cgroup_utils.c
configure.ac
proc_cpuview.c
proc_fuse.c
sysfs_fuse.c
utils.c

support ASAN and UBSAN + bugfixes

---

bindings.c
macro.h

macro: add and use lxcfs_info()

---

lxcfs.c

lxcfs: use lxcfs_info()

---

src/Makefile.am

autotools: fix Makefile

---

src/Makefile.am

man: fix manpage generation

---

src/sysfs_fuse.c

sysfs_fuse: cleanup

---

src/utils.c

utils: cleanup

---

src/lxcfs.c

lxcfs: fix help output

---

src/proc_cpuview.c
src/proc_loadavg.c

proc_{cpuview,loadavg}: fix signed/unsigned check

---

.gitignore
.travis.yml
tests/main.sh
tests/test_cgroup
tests/test_confinement.sh
tests/test_meminfo_hierarchy.sh
tests/test_proc
tests/test_read_proc.sh
tests/test_reload.sh

travis: Enable all architectures

---

src/bindings.c
src/bindings.h
src/cgroup_fuse.c
src/macro.h
src/proc_fuse.c
src/sysfs_fuse.c
src/utils.c
src/utils.h

liblxcfs: handle broken upgrades gracefully

---

src/lxcfs.c

usage: Fix cfs help

---

src/proc_fuse.c

Using unsigned long and uint64_t is problematic on 32bit.

proc_fuse: port to uint64_t

---

src/bindings.c
src/proc_cpuview.c
src/proc_fuse.c
src/proc_loadavg.c

tree-wide: use {u}int64_t types

---

tests/test_sigusr2.sh

test_sigusr2: improve tests

---

src/bindings.c
src/bindings.h
src/lxcfs.c

bindings: introduce set_signal_handler

---

src/cgroup_fuse.c
src/cgroups/cgfsng.c
src/lxcfs.c

cgroup_fuse: fix cgroupfs virtualization needed on non-cgns systems

---

src/utils.h

utils: shut up compiler

---

src/proc_cpuview.c
src/proc_loadavg.c

proc_loadvg: fixes

---

src/cgroups/cgfsng.c
src/cgroups/cgroup_utils.h
src/proc_cpuview.c

tree-wide: add and use must_make_path_relative()

---

src/cgroup_fuse.c
src/cgroups/cgroup_utils.h
src/proc_loadavg.c
src/utils.c
src/utils.h

tree-wide: fixes

---

tests/test_reload.sh

tests: Silence build output

---

src/cgroup_fuse.c
tests/Makefile.am
tests/main.sh
tests/test_readdir

cgroup_fuse: actually make asz check mean something

---

src/proc_fuse.c
src/utils.c
src/utils.h

proc_fuse: improve /proc/meminfo

---

src/proc_fuse.c

The sscanf() line got removed on accident.
Closes #384.

proc_fuse: fix swap calculations

---

.travis.yml

travis: enable coverity integration

---

src/bindings.c

So we don't keep holding it throughout the expensive the
fork/clone/send cycle of figuring out a namespace's init
pid.
Also change some functions to pass the init namespace inode
instead of the process' struct stat, so that it is obvious
that we don't use other parts of the stat info. The reason
is that we previously acquired the store lock before doing
the call to `stat()` and therefore it may not be immediately
obvious that things such as the timestamps found inside the
`struct stat` are not contributing to any race between the
multiple acquisitions of the store lock.

relax init pid store locking a bit

---

src/memory_utils.h

memory_utils: make it easier for Coverity

---

src/cgroups/cgroup_utils.c

cgroups: simplify cgroup_walkup_to_root()

---

src/proc_fuse.c

Stéphane has been running into issues with wrong sawp limits. The logic
he suggested does:
- if memory == memory+swap, we list both at the memlimit for total size
- if memory+swap is larger than memory, then we add the extra amount to
total swap but still cap to physical swap limit
We came to the conclusion that this is currently the best approach as we
show the mem limit as both Memory and Swap so advertising twice as much
as allowed but there's no way around that really or we'd need to
dynamically update both MemTotal and SwapTotal based on what's used to
keep MemTotal+SwapTotal == limit that's certainly doable but it will be
somewhat racy and also likely confused userspace more than mis-reporting
swap.
Signed-off-by: Christian …

proc_fuse: improve swap calculation

---

src/proc_cpuview.c

reset  read_pos=0 after building usage_str

Fix https://github.com/lxc/lxcfs/issues/404

---

src/proc_fuse.c

cpuview: fix /proc/stat virtualization

---

src/bindings.c
src/lxcfs.c
src/macro.h
src/proc_fuse.c
src/proc_loadavg.c

performance tweaks and leak fixes

---

src/proc_fuse.c

swap fixes

---

src/proc_cpuview.c
src/proc_fuse.c
src/utils.c
src/utils.h

proc_fuse: cap swap to global values

---

src/proc_fuse.c

Essentially, we stop being clever. This is just a nightmare.

proc_fuse: more swap tweaks

---

.travis.yml
src/bindings.h
src/lxcfs.c
src/proc_fuse.c

bindings: provide lxcfs_clone() as wrapper around lxcfs_raw_clone()

---

src/cgroups/cgroup.c

Signed-off-by: Ruan Kunliang <PeterRK@126.com>

fix type mismatch

---

configure.ac
src/Makefile.am
src/bindings.c
src/cgroup_fuse.c
src/cgroups/cgfsng.c
src/cgroups/cgroup.c
src/cgroups/cgroup2_devices.c
src/cgroups/cgroup_utils.c
src/cpuset_parse.c
src/fuse_compat.h
src/lxcfs.c
src/lxcfs_fuse_compat.h
src/proc_cpuview.c
src/proc_fuse.c
src/proc_loadavg.c
src/sysfs_fuse.c
src/utils.c

Signed-off-by: Scott Parlane <scott.parlane@alliedtelesis.co.nz>

Add support for fuse3

---

src/proc_fuse.c

diskstats: support new fields in 4.18+ kernels

---

README.md

README: clarify SWAP

---

src/proc_cpuview.c

proc_cpuview: release lock before returning

---

src/lxcfs.c

lxcfs: rework option parsing

---

src/cgroup_fuse.c

cgroup_fuse: replace potentially problematic terminology

---

meson.build

build: fixes

---

meson.build

build: improvements

---

README.md

fix package name,and add tips.
Signed-off-by: Mowei Jiang   moweiraul@gmail.com

fix  package name

---

src/proc_cpuview.c

For issue: https://github.com/lxc/lxcfs/issues/500
Signed-off-by: Nguyen Phan Huy <phanhuy1502@gmail.com>

Skip cpu revise when cfs quota is disable

---

src/cgroup_fuse.c

related issues https://github.com/lxc/lxcfs/issues/505
if system already set systemd.unified_cgroup_hierarchy=1 
```
root@ubuntu-focal:/home/vagrant/lxcfs# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.4.0-91-generic root=UUID=94ab4479-4a78-42cb-9888-bb63d6a79c8c ro systemd.unified_cgroup_hierarchy=1 console=tty1 console=ttyS0
root@ubuntu-focal:/home/vagrant/lxcfs# ls /var/lib/lxcfs/
cgroup  proc  sys
root@ubuntu-focal:/home/vagrant/lxcfs# ls /var/lib/lxcfs/cgroup/
```
the old style , just for regression 
```
root@ubuntu-focal:/home/vagrant/lxcfs# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.4.0-91-generic root=UUID=94ab4479-4a78-42cb-9888-bb63d6a79c8c ro console=tty1 console=ttyS0
root@ubuntu-focal:/home/vagrant/lxcfs# ls /var/lib/lxcfs/
cgroup  proc  sys …
```

empty cgroup dir if set unified_cgroup_hierarchy=1

---

meson.build
src/proc_cpuview.c
src/proc_fuse.c
src/proc_loadavg.c

tree-wide: use PRIu64 to print uint64_t

---

src/proc_fuse.c

Fixes: #516
Signed-off-by: Christian Brauner (Microsoft) <christian.brauner@ubuntu.com>

proc_fuse: improve error message

---

Makefile

Makefile: Fix ordering and add PHONY

---

src/cgroup_fuse.c
src/lxcfs.c
src/lxcfs_fuse.h
src/lxcfs_fuse_compat.h
src/proc_fuse.c
src/sysfs_fuse.c
tests/main.sh.in
tests/meson.build
tests/test_sysfs.in

Signed-off-by: Christian Brauner (Microsoft) <christian.brauner@ubuntu.com>

fuse: set file info for fuse2

---

src/sysfs_fuse.c

Calculate accurate size of 'online' file in sys_getattr routine.
Signed-off-by: huteng.ht <huteng.ht@bytedance.com>

sysfs: correct file size of /sys/devices/system/cpu/online.

---

src/lxcfs.c

When introducing versioned options, we started using fuse's
"init" callback in order to tell the library to set
`can_use_sys_cpu` and `has_versioned_opts` accordingly.
However, we forgot to also do this on a reload. Fix this by
simply calling `lxcfs_fuse_init()` in `do_reload()` as well.
Additionaly: ignore lxcfs_fuse_init()'s return value.
We just "passed through" the private_data from fuse which is
set via the `fuse_main()` call.
It's better to not leave this up to the library anyway in
order to make it easier to be fuse version agnostic in the
future.
Without this, issuing a reload to lxcfs would cause
files in `/sys/devices/system/cpu/` to be visible via
`readdir`, but accessing them would fail:
~ # ls /sys/devices/system/cpu/
ls: /sys/devices/system/cpu/cpuidle: No such file or …

re-initialize library after reload

---

README.md

doc: guide for mount /sys/devices/system/cpu in docker demo
Signed-off-by: blue-troy <12729455+blue-troy@users.noreply.github.com>

doc: guide for mount /sys/devices/system/cpu in docker demo

---

src/bindings.c
src/bindings.h
src/macro.h
src/proc_fuse.c
src/utils.c
src/utils.h

An attempt to address issue https://github.com/lxc/lxcfs/issues/553

cpuinfo with personality

---

config/init/meson.build

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

init: respect --prefix when installing systemd unit files

---

.github/workflows/builds.yml

Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>

github: make coverity workflow work with meson

---

src/proc_fuse.c

We've lost 15th column (discard) in /proc/diskstats output.
After this fix /proc/diskstats format in full agreement with 4.18 kernel. In 5.5+ kernels two new fields were introduced flush_req/flush_time. Unfortunately, we can't add support for them as cgroup doesn't provide us with this stat info.
See also:
https://github.com/torvalds/linux/commit/b6866318657717c8914673a6394894d12bc9ff5e
Fixes #589
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>

proc: fix /proc/diskstats output format

---

src/lxcfs.c

lxcfs: Add startup message

---

.github/workflows/tests.yml

This reverts commit 351775512350bfb45c6486f39a7aa7cc76f690c7.

Revert "github: workaround CI issue with ASAN"

---

.github/workflows/tests.yml
tests/live-upgrade-test.sh.in
tests/meson.build

Let's cherry-pick this to stable-6.0 branch as it will help us to test compatibility between the stable-6.0 and main branch.
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>
(cherry picked from commit e5a5c8c7a5953dbccce5aab3e860f9b13339869a)

github: add lxcfs live upgrade compatibility test (stable-6.0)

---

.github/workflows/tests.yml
tests/live-upgrade-test.sh.in
tests/meson.build

Let's cherry-pick this to stable-5.0 branch as it will help us to test compatibility between the stable-5.0 and main branch.
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>
(cherry picked from commit e5a5c8c7a5953dbccce5aab3e860f9b13339869a)

github: add lxcfs live upgrade compatibility test (stable-5.0)

---

src/bindings.h

Add missing linux/limits.h include

---

meson.build
src/bindings.c
src/cgroups/cgroup.c
src/cgroups/cgroup_utils.c
src/cgroups/cgroup_utils.h
src/cpuset_parse.c
src/lxcfs.c
src/utils.c
src/utils.h
tests/test-read.c

Fixes: Coverity 382190
Fixes: Coverity 382186
Fixes: Coverity 382195
Fixes: Coverity 451805

A bunch of Coverity warnings fixes
