lxc/lxcfs

lxcfs.c
See bug #24 - in at least one situation, FUSE sends lxcfs unexpectedly small read requests, which results in truncated snprintfs. This PR checks every relevant snprintf and returns 0 on error or truncation.
NOTE: it's possible that a better solution would be to simply return the truncated buffer, caching the generated contents and serving the rest to future small reads with offsets, but this appears to be so rare (only on /proc/uptime, from a container in the process of stopping, on some trusty systems) that it isn't worth the effort. I'm open to arguments to the contrary, however.
=> Add error handling for snprintf calls inside *_read() funcs

README.md
At first glance, I thought this project was a custom fs for the hosts, not for the containers themselves.
Hopefully this line will clear up the misunderstanding for future readers, and show that this project is *really* useful! (e.g. it fixes applications looking at `/proc/{cpu,mem}info`.)
=> Better explain what lxcfs does

lxcfs.c, tests/test_proc
/proc/uptime has the format %lu.%02lu %lu.%02lu. The format used by
lxcfs doesn't consider the nano second portion of the uptime which might
cause programs that rely on that format to fail.
This commit adapts the uptime format to match the kernels by adding
trailing dummy values (.0) to the uptime and idle time values.
The parsing of /proc/uptime was updated.
Signed-off-by: Bernhard Miklautz <bernhard.miklautz@shacknet.at>
=> Change uptime format

cgfs.c
tl;dr realloc only in BATCH_SIZE increments.
longer version
I can't reproduce it separately yet, but on i386 xenial, lxcfs
is failing on reading meminfo, hitting a glibc assertion in malloc.c:
lxcfs: malloc.c:2373: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
The relevant glibc code:
/*
If not the first time through, we require old_size to be
at least MINSIZE and to have prev_inuse set.
*/
assert ((old_top == initial_top (av) && …
=> work around weird glibc assert

lxcfs.c
See comment for details.
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>
=> caller_may_see_dir: correctly handle tasks in /

.gitignore, tests/test_cgroup, tests/test_confinement.sh, tests/test_meminfo_hierarchy.sh, tests/test_read_proc.sh
With this, we should be able to run more than one testsuite at once.
=> Don't hardcode strings in testsuites

Makefile.am, config/Makefile.am, config/init/Makefile.am, config/init/systemd/Makefile.am, config/init/systemd/lxcfs.service, config/init/sysvinit/Makefile.am, config/init/sysvinit/lxcfs.init, config/init/upstart/Makefile.am, config/init/upstart/lxcfs.conf, configure.ac
Mostly copied from the Ubuntu package.
Note someone still needs to write the bsd and gentoo init
scripts.  (You can look at the sysvinit jobs here and the
bsd+gentoo jobs in git://github.com/lxc/cgmanager for
inspiration).
Closes #71
=> Add upstart and systemd init jobs

share/lxc.mount.hook.in
It's not very reliable (had it fail on one of my servers) and since
we're already iterating through a list of mountpoints, it's also
completely unneeded.
=> hook: don't use mountpoint

config/init/upstart/lxcfs.conf
Otherwise lxcfs keeps lxc from hitting state 'started', which
in turn blocks reboot/shutdown.
=> upstart: change how we decide to not run in a container

share/lxc.mount.hook.in
=> hook: Don't fail when root mountpoint is a symlink

bindings.c, lxcfs.c
If cgroupv2 is enabled either alone or together with legacy hierarchies
/proc/self/cgroup can contain entries of the form:
0::/
This will cause lxcfs to fail the cgroup mounts because it parses out the empty
string "" and later on passes it to mount(). Let's skip such entries.
=> skip empty entries under /proc/self/cgroup

bindings.c, bindings.h, lxcfs.c
lxcfs now creates a private mount namespace (actually rather a minimal chroot)
to hide its cgroup mounts under BASEDIR/ from other processes that would get
confused by it. However, the fuse mount usually placed under /var/lib/lxcfs (or
whatever the user gives us via argv[1]) needs to be visible in the initial
namespace. Hence, we place these mounts in different namespaces. ~~This requires
some coordination. fuse_mount() needs to be called in the initial namespace.
Afterwards we can unshare(CLONE_NEWNS), setup the cgroup mounts and create our
minimal chroot. On failure we need to switch back to the initial mount namespace
for fuse_umount() to succeed.
In addition, when we are asked to reload our dynamic library, we also need to
switch to the initial mount namespace.~~
Signed-off-by: …
=> move lxcfs to minimal chroot

lxcfs.c
otherwise this generates "funny" manpages like
/home/remote/egolov/Devel/lxcfs/.libs/lt-lxcfs [-p pidfile] mountpoint
/home/remote/egolov/Devel/lxcfs/.libs/lt-lxcfs -h
or
/build/lxcfs-8lNGve/lxcfs-2.0/.1/.libs/lt-lxcfs [-p pidfile] mountpoint
/build/lxcfs-8lNGve/lxcfs-2.0/.1/.libs/lt-lxcfs -h
Signed-off-by: Evgeni Golov <evgeni@debian.org>
=> don't use argv[0] in usage output

bindings.c
We do not need to check whether mode & W_OK is passed in. Even if the cgroup
root mount is writeable operations like cg_mkdir() et al. will fail with e.g.
EPERM. Basically all operations will fail on the cgroup root mount point because
the first operation they perform is pick_controller_from_path(). That is to say
they try to e.g. pick "blkio" from /var/lib/lxcfs/cgroup/blkio/some/cgroups an
similiar for all other controllers. If pick_controller_from_path() fails they
all return an appropriate errno. For example, cg_mkdir() does:
controller = pick_controller_from_path(fc, path);
if (!controller)
return errno == ENOENT ? -EPERM : -errno;
This means, we do not need to return an errno already in cg_access when
mode & W_OK is passed in. This has the advantage that users are still able to …
=> bindings: revert cgroup check and improve fs behavior

bindings.c
We should only deny getting the attributes of a file if it neither contains
`O_RDONLY` permission nor `O_WRONLY` permissions. Otherwise `ls -al` will not show
attributes on `O_WRONLY` files. Such files are quite common under `/proc` or `/sys`.
BEFORE:
```
root@conventiont:~# ls -al /var/lib/lxcfs/cgroup/devices/
ls: cannot access '/var/lib/lxcfs/cgroup/devices/devices.allow': Permission denied
ls: cannot access '/var/lib/lxcfs/cgroup/devices/devices.deny': Permission denied
total 0
drwxr-xr-x 2 root root 0 Oct  7 01:00 .
drwxr-xr-x 2 root root 0 Oct  7 01:00 ..
-rw-r--r-- 1 root root 0 Oct  7 01:00 cgroup.clone_children
-rw-r--r-- 1 root root 0 Oct  7 01:00 cgroup.procs
-r--r--r-- 1 root root 0 Oct  7 01:00 cgroup.sane_behavior
?????????? ? ?    ?    ?            ? devices.allow …
```
=> bindings: allow getattr on O_WRONLY files

bindings.c
Unless the file was created with chmod 000 the current check for
!O_RDONLY && !O_WRONLY will always be successful, making the current check
basically a noop. And even in the case where a file has chmod 000 we still want
the user to see that it has no permissions. So let's remove the check entirely.
Whether a user sees a file will be determined by a prior check for O_RDONLY on
the directory anyway.
Signed-off-by: Christian Brauner <christian.brauner@canonical.com>
=> bindings: remove noop check

bindings.c
the missing : makes the other branches for lines starting with "Active" and "Inactive" unreachable, leading to /proc/meminfo content like this:
...
Active:            24484 kB
Inactive:           7468 kB
Active:            24484 kB
Inactive:           7468 kB
Active:            24484 kB
Inactive:           7468 kB
...
instead of:
...
Active:            16020 kB
Inactive:        8372040 kB
Active(anon):      14580 kB
Inactive(anon):    14868 kB
Active(file):       1440 kB
Inactive(file):  8357172 kB
...
Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>
=> fix Active/Inactive /proc/meminfo

Makefile.am, bindings.h, macro.h, pam/pam_cgfs.c
This is a rewrite of pam_cgfs which leans on LXC's cgfsng.c. Various codepaths
have been adapted and made more appropriate.
The strategy of pam_cgfs v2 is to support cgroupfs v1, cgroupfs v2, and mixed
mounts where some controllers are mounted into a standard cgroupfs v1 hierarchy
location (/sys/fs/cgroup/<controller>) and other controllers are mounted into
the cgroupfs v2 hierarchy.
The functions and types for cgroupfs v1 and cgroupfs v2 have nearly all been
kept separately even if they do nearly the exact same job. This is on purpose!
Although marked non-experimental, cgroupfs v2 is too much of a moving target.
Extrapolating from currentl cgroupfs v2 standard behaviour seems risky and error
prone. Even more so when those assumptions complexify or simplify cgroupfs v1
assumptions when …
=> pam_cgfs: reimplement and add cgroupfs v2 support

pam/pam_cgfs.c
If init has not placed us into our own cgroup on login we will reside in the
root cgroup. In this case cgroup.clone_children will not have been initialized
and so we need to do it. Otherwise users will not be able to start containers
with cpuset limits set.
Signed-off-by: Christian Brauner <christian.brauner@canonical.com>
=> pam_cgfs: handle cgroupfs v1 cpuset controller

bindings.c
/proc/meminfo displays wrong value.
```
lxcfs on /proc/meminfo type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
cache 8593408
Cached:                0 kB
```
Signed-off-by: KUWAZAWA Takuya albatross0@gmail.com
=> Fix wrong scanning of memory.stat

tests/test_cgroup, tests/test_proc
Turns out a MB of memory isn't quite enough to run things like cat on
some architectures, so lets bump to a more comfortable 64MB.
=> tests: Fix run on ppc64el

bindings.c
lxcfs seems to crash in cg_rmdir while phpsessioncleanup is running in many containers simultaneously.
Here is a stack trace:
```
Detaching after fork from child process 17921.
Reading in symbols for ../sysdeps/x86_64/multiarch/../strcmp.S...done.
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fba74fc4700 (LWP 214112)]
__strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:1358
1358    ../sysdeps/x86_64/multiarch/../strcmp.S: No such file or directory.
Reading in symbols for ../sysdeps/unix/sysv/linux/x86_64/clone.S...done.
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:1358
No locals.
#1  0x00007fba75099de3 in cg_rmdir () from /usr/lib/lxcfs/liblxcfs.so
No symbol table info available.
#2  0x000055952dda6c8e in ?? ()
No symbol table …
```
=> Also check next variable for NULL on cg_rmdir

bindings.c
We do this for the memlimit when hitting MemTotal which
means if neither is limited we end up subtracting the
hosts's total memory from the 'unlimited' swap value in the
SwapTotal and SwapFree lines.
Fixes #170
=> Limit memswlimit by TotalSwap

bindings.c
Currently, the 'btime' of /proc/stat reflects the boot time of the host.
We would like it to reflect when the guest boots, so use the start time of
init.
Signed-off-by: Jason Baron <jbaron@akamai.com>
=> virtualize the 'btime' field of /proc/stat

pam/pam_cgfs.c
When we detected the unified cgroup hierarchy we actually need to report back that we did. Otherwise we might needlessly fail later on.
=> pam: bugfixes

bindings.c
Closes #189
This seems to be responsible for corrupting STIME on processlist
inside containers.  Hopefully we can find a reasonable way to fix
both, but compared to unvirtualized btime field, bogus STIME field
is the greater evil here.
Signed-off-by: Serge Hallyn <serge@hallyn.com>
=> (temporarily?) revert the virtualization of btime field in /proc/stat

config/init/sysvinit/lxcfs
otherwise init might try to start lxcfs before cgroupfs was mounted,
which will result in an empty /var/lib/lxcfs/cgroup and weird issues.
Debian-Bug: https://bugs.debian.org/859219
Signed-off-by: Evgeni Golov <evgeni@debian.org>
=> add cgroupfs-mount to Should-Start/Stop sysvinit LSB headers

bindings.c
When doing subsequent reads of uptime on an open file handle
in the form:
read
lseek 0L, SEEK_SET
read
the second (and later) reads cause that the error
"failed to write to cache" was printed. This
happens for example with "top". top would print the error:
bad data in /proc/uptime
To fix this problem use the whole size of the buffer instead of the d->size
because this is set on the first read.
This behavior was introduced with commit 0ecddf023a4caf8e8d2fe7e9125d777a06c5ec12.
Signed-off-by: Bernhard Miklautz <bernhard.miklautz@shacknet.at>
=> uptime: fix a problem with subsequent reads.

Makefile.am, configure.ac
This patch fixes the target installation directory for liblxcfs. do_reload function in lxcfs.c looks for the library in ${libdir}/lxcfs but the autotools installs it in ${libdir}
Testing:
With this patch, install gives following output:
```bash
/bin/mkdir -p '/usr/local/bin'
/bin/bash ./libtool   --mode=install /usr/bin/install -c lxcfs '/usr/local/bin'
libtool: install: /usr/bin/install -c lxcfs /usr/local/bin/lxcfs
/bin/mkdir -p '/usr/local/lib/lxcfs'
/bin/bash ./libtool   --mode=install /usr/bin/install -c   liblxcfs.la '/usr/local/lib/lxcfs'
libtool: install: /usr/bin/install -c .libs/liblxcfs.so /usr/local/lib/lxcfs/liblxcfs.so
libtool: install: /usr/bin/install -c .libs/liblxcfs.lai /usr/local/lib/lxcfs/liblxcfs.la
libtool: finish: …
```
=> Fix the installation directory for liblxcfs to ${libdir}/lxcfs

bindings.c
it make the value of (memswlimit - memlimit) to be swaptotal,
it is wrong, because swapsize in cgroup/container can up to
[0,memswlimit], sometimes if the memsize(unless swap) of all tasks in
cgroup/container is very small, the swaptoal can to be memswlimit
so make the swaptotal to be min(host swtoal,memswlimit)
Signed-off-by: yuwang.yuwang <yuwang.yuwang@alibaba-inc.com>
=> Fix wrong calc of swaptoal and swapfree

bindings.c, pam/pam_cgfs.c
In order to enable proper unprivileged cgroup delegation on newer kernels we not
just need delegate the "cgroup.procs" file to the user but also to
"cgroup.threads". But don't report an error in case it doesn't exist.
Also delegate "cgroup.subtree_control" to enable users to hand over controllers
to descendant cgroups.
=> pam: cgroup v2 fixes

bindings.c
The values for Cached, Active, Inactive, Active(anon), Inactive(anon),
Active(file), Inactive(file), and Unevictable are derived/computed
from these values in the relevant meminfo.stat:
cache
active_anon
inactive_anon
active_file
inactive_file
unevictable
However, these value apply only to the cgroup of the lxc container
itself.  If your container uses memory cgroups internally, and thus
the container cgroup has children, their memory is not counted.
In order to take the memory usage of child cgroups into account, we
need to look at the "total_" prefixed versions of these values.
Signed-off-by: Aaron Sokoloski <asokoloski@gmail.com>
=> Fix inaccurate values in /proc/meminfo for containers with child cgroups

bindings.c
MemAvailable represents roughly how much more memory we can use before
we start swapping.  Page cache memory can be reclaimed if it's needed
for something else, so it should count as available memory.  This
change should also fix the "available" column of the "free" command,
as well as the "avail Mem" value in "top", both of which come from
MemAvailable.
Note that this isn't perfectly accurate.  On a physical machine, the
value for MemAvailable is the result of a calculation that takes into
account that when memory gets low (but before it's completely
exhausted), kswapd wakes up and starts paging things out.  See:
https://github.com/torvalds/linux/blob/a0908a1b7d68706ee52ed4a039756e70c8e956e9/mm/page_alloc.c#L4553
(si_mem_available function)
I tried to think of a way to be more exact, but …
=> Change MemAvailable figure in /proc/meminfo to include cache memory -- Fixes #175 I think.

bindings.c, bindings.h, lxcfs.c
Per-container loadavg tracking is not working after library reload using `SIGUSR1`. When reloading the library in `do_reload()`, the thread that is tracking per-container loadavgs is left running. As I understand it, it continues to operate on those static variables from the original library. loadavg is not set up using the new library and so `proc_read_loadavg()` starts to return the host's `/proc/loadavg`, as if it was disabled.
This patch stops the loadavg thread before closing the original library and restarts it when the new library is loaded.
=> loadavg: restart thread on library reload

bindings.c
`line` is allocated by `getline()`, but it's not freed.
=> bindings: fix memory leak in calc_pid()

bindings.c
=> bindings: better logging for write_string()

bindings.c
=> bindings: prevent double free

tests/test_syscalls.c
=> tests: include missing sys/sysmacros.h header

bindings.c
Fixes: https://bugs.launchpad.net/ubuntu/+source/lxcfs/+bug/1807628
=> bindings: prevent NULL pointer dereference

bindings.c
This reverts commit 0108dc1cc6eab76392d228ee4ca844729096473d.
I am still experiencing hangs in lxcfs even with this patch.
I redid this PR to remove some of the extra history that had been included in the last one.
CC @brauner @Blub
=> Revert "bindings: protect do_release_file_info() with mutex"

.gitignore, Makefile.am, configure.ac, lxcfs.spec.in, share/lxc.mount.hook.in
hooks: Modifies lxc.mount.hook to skip mounting lxcfs cgroup tree when running CentOS 7 on the host.
This is due to instabilities when running lxcfs on CentOS 7 hosts.
/proc mounts do not cause any problems, so those are not skipped.
systemd containers still start OK with cgroup tree not mounted into lxcfs on CentOS 7 hosts.
Signed-off-by: tomponline <tomp@tomp.uk>
CC @Blub @brauner
=> hooks: skip mounting lxcfs cgroup tree on centos 7 hosts

README.md, bindings.c, bindings.h, lxcfs.c
Signed-off-by: Dieter Maier <dma@web.de>
It concerns the combination of a system with activated swap and docker. When I use lxcfs to limit the memory resources of a container, I always have swap.. Which I don't want.
docker run -it -m 256m --memory-swap 256m \
-v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
-v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw \
-v /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw \
-v /var/lib/lxcfs/proc/stat:/proc/stat:rw \
-v /var/lib/lxcfs/proc/swaps:/proc/swaps:rw \
-v /var/lib/lxcfs/proc/uptime:/proc/uptime:rw \
ubuntu:18.04 /bin/bash
That, too, is not satisfactory:
docker run -it -m 256m \
-v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
....
I can force with the parameter "-u" that the swap values in the "meminfo" are always 0.
To use this parameter I …
=> option to disable swap in meminfo

Makefile.am, README.md, bindings.c, bindings.h, lxcfs.c, sysfs_fuse.c, sysfs_fuse.h
Support /sys/devices/system/cpu/online， to make applications that use sysconf (_SC_NPROCESSORS_ONLN) happy.
Partially resolve #88 .
=> Support /sys/devices/system/cpu/online

share/lxc.mount.hook.in
Mount `/sys/devices/system/cpu/online` introduced by #278.
=> mount hook: mount /sys/devices/system/cpu/online

bindings.c
When the shared library is reloaded but the lxcfs binary itself will
likely not be replaced and even if will still be in-memory, i.e. the
fuse loop will not be restarted.
The code here introduced a new struct lxcfs_opts which is allocated and
gets stashed in the private_data member of the fuse file when the lxcfs
binary is first called. Now, in a scenario where the shared library is
reloaded the lxcfs binary itself won't be re-run. So now we have a
shared library that assumes there's always a valid struct lxcfs_opts
stashed in the private_data member. But there isnt'. This very likely
causes the segfaults we have seen.
Fix it by verifying a struct has been stashed.
Fixes: 7e60aa1b1540 ("option to disable swap in meminfo")
=> bindings: ensure that opts is non NULL

macro.h
Originally, the compiler complained:
macro.h:7:25: error: expected expression before ')' token
__func__, __VA_ARGS__);
The reason is that GCC wouldn't abandon `,` when `__VA_ARGS__` is empty.
For emaple:
```
#define eprintf(format, ...) fprintf (stderr, format, __VA_ARGS__)
eprintf("success!\n", );
→ fprintf(stderr, "success!\n", );
```
According to GCC doc, it's okay when adding `##` before `__VA_ARGS__`:
```
#define eprintf(format, ...) fprintf (stderr, format, ##__VA_ARGS__)
eprintf ("success!\n")
→ fprintf(stderr, "success!\n");
```
=> macro: fix lxcfs_{error,debug,v} build error when __VA_ARGS__ is empty

bindings.c
Signed-off-by: Hongbo Yin <yinhongbo@bytedance.com>
This commit fix container run host pid namespace, the initpid will return 1.
then in same case lxcfs will get a lot of error, like this:
```
Aug  5 14:54:11 n10-019-024 lxcfs[3131]: bindings.c: 4503: cpuview_proc_stat: cpu23 from / has unexpected cpu time: 3954948 in /proc/stat, 4062974 in cpuacct.usage_all; unable to determine idle time
```
In some scenarios, the cgroup count is not accurate, which will cause the "/" counter to be greater than the system /proc/stat
so if initpid==1  we need return host os's /proc/stat. Instead of getting the data in the cgroup.
=> fix container run pid host mode /proc/stat error log

bindings.h, cpuset.c, sysfs_fuse.c
When the container runs in cpuset and cpu quota, for example, cpu quota is limited to 8 cores, cpuset is limited to 1-3, 4-5, then there will be problems. The core number obtained by /proc/cpuinfo is 4 cores, and /sys /devices/system/cpu/online gets 8 cores.
The reason is that /sys/devices/system/cpu/online does not take into account the situation of cpuset. So submit this patch.
Test case:
`docker run -it -d  --cpuset-cpus="1-2,3-4" \
--cpu-period=100000 \
--cpu-quota=800000 \
--memory 2048m \
-v /root/tce/lxcfs/run/lxcfs/sys/devices/system/cpu/online:/sys/devices/system/cpu/online \
-v /root/tce/lxcfs/run/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
debian:latest bash
`
Signed-off-by: Hongbo Yin <yinhongbo@bytedance.com>
=> fix /sys/devices/system/cpu/online in cpuset not correct bug

bindings.c
This PR fix is similar to #125 
This type of problem is mainly due to a bug in the read_file function. The reason for this bug will be analyzed below.
Under some Case, We execute ps aux in the container and we get an error in not finding btime.
```
58eb38977abb(@:):/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
missing btime in /proc/stat
root           1  0.0  0.0 205172  7412 ?        Ss58eb38977abb(@:):/#
58eb38977abb(@:):/#
```
Then we use strace to track system calls.
```
58eb38977abb(@:):/# strace -ff -s 10240 -e read,open,openat ps aux > /dev/null
...  ...
open("/proc/stat", O_RDONLY)            = 6
read(6, "cpu  13030938 7115021 44303748 6188805307 13413081 0 182664 0 0 0\ncpu0 333372 172944 1060094 154237893 267468 0 13827 0 0 0\ncpu1 414513 …
```
=> fix read_file second reading empty bug

bindings.c
Changed the logic used for SwapFree when swap accounting is enabled to better handle situations where memswusage is less than memusage, caused by the fuzziness of the usage_in_bytes counters used as the source.
Signed-off-by: Kellen Renshaw <kellen.renshaw@canonical.com>
=> handle swap reporting better when swap accounting is enabled

bindings.c, cgroups/cgfsng.c, cgroups/cgroup.h
cgroup2's io controller does not support most of the blkio files.
=> bindings: port blkio to new cgroup getters

bindings.c, macro.h
- Improve naming for {con,de}structor.
- Fail when we can't setup cgroups.
=> bindings: rework {con,de}structor

cgroups/cgfsng.c, cgroups/cgroup.h, proc_fuse.c, proc_loadavg.c
dirty/writeback  ... and so on
Closes #315.
Signed-off-by LiMing Wu <19092205@suning.com>
=> meminfo: add some more metrics

proc_fuse.c
=> proc_fuse: ensure struct memory_stat is properly zeroed

proc_fuse.c
Signed-off-by: Irnes Mujkanovic <irnes.mujkanovic@gmail.com>
=> meminfo: fix used/cache memory calculation under cgroup2

README.md, cgroup_fuse.h, configure.ac, macro.h, proc_fuse.h, sysfs_fuse.h
There's no need for anyone to call dlsym() on anything else than what we
explicitly support.
=> tree-wide: switch default visibility to hidden

src/cgroups/cgfsng.c, src/proc_cpuview.c, src/proc_fuse.c
Implementation is debatable and minimal, but this was required to have at least `/proc/stat`, `/proc/cpuinfo`, `/proc/meminfo`, and `/sys/devices/system/cpu/online` behave under a unified layout.
=> Unified cgroup fixups

configure.ac, src/proc_cpuview.c
Both are standard in LXC for a long time now. And gcc-4.8 which is the
minimal compiler version we require (same as the Linux kernel) deals
with this.
Closes #362.
=> configure: add -Wvla and -std=gnu11

src/bindings.c, src/lxcfs.c
=> lxcfs: fix shared library reload

src/bindings.c, src/proc_fuse.c, tests/Makefile.am, tests/main.sh, tests/test_sigusr2.sh
When LXCFS has a bug and provides wrong or inconsistent values user
often want to turn off virtualization until we have figured out a fix
and rollout an upgrade to reload the shared library. Allow them to
toggle between virtualization mode and non-virtualization mode by
sending SIGUSR2 to lxcfs:
Kernel supports pidfds
api_extensions:
- cgroups
- sys_cpu_online
- proc_cpuinfo
- proc_diskstats
- proc_loadavg
- proc_meminfo
- proc_stat
- proc_swaps
- proc_uptime
- shared_pidns
- cpuview_daemon
- loadavg_daemon
- pidfds
Switched into non-virtualization mode
Switched into virtualization mode
Switched into non-virtualization mode
Switched into virtualization mode
Switched into non-virtualization mode
=> lxcfs: allow users to switch between virtualization and non-virtualization mode

src/cgroups/cgfsng.c
=> cgroups: remove unused function

src/Makefile.am, src/bindings.c, src/cgroups/cgroup2_devices.h, src/syscall_numbers.h, src/utils.h
The same thing that I did for LXC.
=> tree-wide: add and use syscall_numbers.h

src/proc_fuse.c
Some lines of /proc/meminfo can be prefixes of the other, 
e.g. `Writeback:` and `WritebackTmp:`
This means that in order to to precise match, the code should always match up until `:`
=> Fix #387. Include `:` in matching of lines in /proc/meminfo

src/bindings.c
=> bindings: use zalloc()

src/cgroups/cgfsng.c, src/cgroups/cgroup.c, src/cgroups/cgroup.h, src/cgroups/cgroup_utils.c, src/cgroups/cgroup_utils.h, src/proc_fuse.c, tests/test_readdir
Try too read a valid value from a given cgroup file. If it is a legacy
cgroup hierarchy and we fail to find a valid value we terminate early
and report an error.
The cgroup2 hierarchy however, has different semantics. In a few
controller files it will show the value "max" or simply leave it
completely empty thereby indicating that no limit has been set for this
particular cgroup.  However, that doesn't mean that there's no limit. A
cgroup further up the hierarchy could have a limit set that also applies
to the cgroup we are interested in. So for the unified cgroup hierarchy
we need to keep walking towards the cgroup2 root cgroup and try to parse
a valid value.
=> cgroups: more cgroup2 fun

src/cgroups/cgroup_utils.c
=> cgroups: please Coverity

src/proc_fuse.c
We get a positive result with an empty string if we do not
encounter any limits while walking up the cgroup.
=> proc_fuse: silence error when we find no memlimit

src/sysfs_fuse.c, tests/test_proc
To stop the immediate bleeding.
Closes #401.
=> sysfs: cpuinfo: show cgroup cpuset value

src/sysfs_fuse.c
=> sysfs_fuse: remove logically dead code

src/bindings.c
We were stupidly always hashing entry->ino where entry was just freshly
allocated zeroed-memory so we effectively added stuff to the cache
forever but this meant:
- we never found a match when we hashed the actual inode
- we kept growing the cache
- we leaked memory
Closes: #407.
=> bindings: fix init pid hashing

src/utils.c
The epoll socket create error message fails to expand errno, leading to log output like this:
```
Sep 02 05:48:46 hex-128c1-pm lxcfs[2952544]: utils.c: 188: wait_for_sock: Failed to create epoll socket: %m
Sep 02 05:48:46 hex-128c1-pm lxcfs[2952544]: utils.c: 244: recv_creds: Timed out waiting for scm_cred: Too many open files
Sep 02 05:48:46 hex-128c1-pm lxcfs[2057266]: utils.c: 188: wait_for_sock: Failed to create epoll socket: %m
Sep 02 05:48:46 hex-128c1-pm lxcfs[2057266]: utils.c: 280: send_creds: Too many open files - Failed getting reply from server over socketpair: 2
```
=> fix epoll create socket error message

src/proc_fuse.c
`dirname()` behaves differently on `glibc` vs POSIX implementations (e.g. `musl`).
Under `glibc`, the use of `dirname()` terminates at `/` as required, but the same code on `musl` ends at, for example, `/lxc.payload.dear-raccoon`, resulting in an infinite loop when trying to read `/proc/meminfo` in a container.
A simple replacement for `dirname()` solves this on non-`glibc` platforms like Alpine. :smile:
=> Fix `get_min_memlimit()` on non-glibc

src/proc_fuse.c
=> meminfo: show host swap values when no limit or equal limits are set

src/cgroups/cgfsng.c, src/cgroups/cgroup.h, src/proc_fuse.c
This lines up LXCFS with what's described in the README.
Also fixes a few bugs in how `/proc/swaps` was handled.
=> Rework swap memory management

src/proc_cpuview.c
There is a small typo in src/proc_cpuview.c.
Should read `through` rather than `throuh`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, throuh -> through

src/proc_fuse.c, src/sysfs_fuse.c
fixes: #448 caused by 25982f5d7e008e6ad13df28af3006ab8286f4c97
Signed-off-by: Scott Parlane <scott.parlane@alliedtelesis.co.nz>
=> Determine the file size from the current system file size

src/proc_fuse.c
Fixes: https://discuss.linuxcontainers.org/t/lxcfs-spamming-syslog-with-logs-lxc-payload-container-has-unexpected-cpu-time-unable-to-determine-idle-time
Fixes: https://github.com/lxc/lxcfs/issues/464
=> proc_fuse: don't spam log needlessly

src/proc_cpuview.c
Fixes: #472
Reported-by: ycaibb@gmail.com
=> proc_cpuview: unlock mutex in all error paths

src/bindings.c, src/bindings.h, src/proc_fuse.c
Also deduplicates some common code there.
An alternative to the cgv2 check inside `proc_fuse.c` would be to move the mem/swap/memsw-sum logic into the cgroup ops, not sure if it's worth it.
=> make meminfo and swaps cgroupv2 aware

src/proc_fuse.c
Some of these missed the spaces in between and in order to
make this more readable and apparent, put one field per line
and add comments matching the field names.
NOTE: This is basically the same issue as in #512, but on master, so something's fishy here.
=> fix and reformat format strings

.gitignore, src/proc_cpuview.c
- For issue https://github.com/lxc/lxcfs/issues/513
- Currently, value in /proc/stat will be reset when cpuset of the cgroup is updated
- Total cpu usage shown for the cgroup will always be the sum of all actual CPUs, regardless of the active/inactive CPUs
- CPU time of individual "rendered"/"virtual" CPUs for the cgroup will be split according to the online CPUs, such that the sum of all "rendered"/"virtual" CPUs will add up to the cgroup's sum cpu usage (1st line in /proc/stat)
- When cpuset/cfs_quota_us of the cgroup is changed, the cpu time of each core might be resetted (can't avoid for now, since the number of "rendered"/"virtual" CPUs can be changed), but the sum cpu time is unchanged.
- Detailed formula is in the comment of the code change
- Screencast …
=> Preseve cpu sum in /proc/stat when cpuset changes

.github/workflows/coverity.yml, .github/workflows/test.yml, meson.build, meson_options.txt
Documentation was removed from the build system with the migration to
meson. This implements the help2man generation which existed in the
autoconf setup.
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> meson: Include documentation

config/init/meson.build
Hardcoding `/lib` makes meson create a directory which would conflict on
distros with usrmerge as `/lib` is a symlink. We define `libdir` in the
top-level so we should be using that instead.
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> init/meson: Use libdir instead of hardcoded /lib path

config/init/meson.build
This queries the systemd system unit directory instead of hard-coding it.
I would prefer this over #527.
=> Query systemd system unit dir.

.github/workflows/test.yml, meson.build, src/bindings.c, src/lxcfs_fuse_compat.h, src/sysfs_fuse.c, src/utils.c, src/utils.h
Signed-off-by: Christian Brauner (Microsoft) <christian.brauner@ubuntu.com>
=> sysfs_fuse: fixes

meson.build, meson_options.txt
We'd like to provide an easy upgrade path which doesn't
cause an lxcfs-reload to crash because the new library was
built against the wrong version.
=> support explicit fuse version choice

src/proc_fuse.c
on lxc
$ head -2 /proc/stat 
cpu   12846 0 3181 19349 511 122 59 0 0 0
cpu0 2909 0 787 5126 157 32 14 0 0 0
on host
$ head -2 /proc/stat 
cpu  13271 0 3449 33618 565 176 96 0 0 0
cpu0 3012 0 854 8685 171 48 25 0 0 0
Signed-off-by: Tuomas Yrjölä <mail@yrhki.fi>
=> proc_fuse: extra space in /proc/stat

src/utils.c
¡Hola!
While browsing your code I noticed this comment occurs twice.
Change should be self explanatory.
Cheers
=> util: remove doubled comment

src/sysfs_fuse.c
cleanup useless parameters and local variables, meanwhile,
a compiler warning resolved.
Signed-off-by: huteng.ht <huteng.ht@bytedance.com>
=> sysfs: cleanup sys_devices_system_cpu_online_getsize

src/proc_cpuview.c
lxcfs `sys/devices/system/cpu/online` returns 0, when cgroup v2 is enabled and run with `--enable-cfs` and cpu quota is not set.
In cgroup v2, the first column of cpu.max will be a string: "max" if no cpu quota is set. `read_cpu_cfs_param --> sscanf` function fails to parse `"max"` as a number and return zero cpu count.
If cpu controller is not enabled, there is no `cpu.max` file in cgroup dir. It also lead to `max_cpu_count` func returns zero.
https://github.com/lxc/lxcfs/blob/lxcfs-5.0.0/src/proc_cpuview.c#L422
https://github.com/lxc/lxcfs/blob/lxcfs-5.0.0/src/proc_cpuview.c#L479
In cgroup v1, if `cfs_quota_us = -1`, `max_cpu_count` returns cpu count in cpuset: 
https://github.com/lxc/lxcfs/blob/lxcfs-5.0.0/src/proc_cpuview.c#L489
This patch will fix this bug for cgroup v2 env.
=> cgroup v2: /sys/devices/system/cpu/online returns zero

src/sysfs_fuse.c, src/utils.c, src/utils.h
`opathdir` was used to replace `opendir` in order to ensure
`O_NOFOLLOW` and `O_CLOEXEC` were set, however it also added
`O_PATH` which prevents `readdir`/`getdents` to be used on
it, causing the `/sys/devices/system/cpu/<subdir>`
directories to be empty.
Instead, let's have an `opendir_flags` utility which simply
passed additional flags to the `open(..., O_DIRECTORY)` call
preceding `fdopendir()`.
=> replace opathdir with opendir_flags

src/bindings.c, src/lxcfs.c
With fuse3 `fuse_get_context` returns NULL before fuse was
fully initialized, so we must not access it.
Futher, we call 'do_reload' for normal initialization as
well, so let's prevent that from re-initializing the
bindings initially and only do this on actual reloads,
otherwise we do it twice on startup.
Signed-off-by: Wolfgang Bumiller <wry.git@bumiller.com>
Fixes #549
=> fix reinitialization with fuse3

config/init/systemd/lxcfs.service.in, config/init/sysvinit/lxcfs, config/init/upstart/lxcfs.conf
Disable oom killing entirely to minimize the hassle comes from
lxcfs exiting unexpectedly, e.g. the mountpoint got lost.
Signed-off-by: Teng Hu <huteng.ht@bytedance.com>
=> set oom_score_adj of lxcfs process to -1000

src/bindings.c
The relevant code was added in commit 35acc24, but the function/macro prctl_arg() didn't seem to be defined anywhere in the repo. lxc currently has a corresponding macro defined in src/lxc/macro.h that casts the value to an unsigned long. But 0 doesn't require any special handling, so remove the call to prctl_arg().
Verified that the code compiles properly on Debian's ia64 porterbox (yttrium).
=> Fix build on ia64

src/proc_fuse.c
When the kernel has an offline CPU, it only renders the online CPUs in /proc/stat.
When in non-use_view mode, /sys/devices/system/cpu/online shows the CPU numbers as they actually are on the physical system, but /proc/stat used "virtual" (i.e. always zero-indexed) numbers, which causes confusion for some applications. Let's use the same use_view logic in /proc/stat as well.
(root) ~ # chcpu -d 4
CPU 4 disabled
(root) ~ # cat /sys/devices/system/cpu/online
0-3,5-7
(root) ~ # cat /proc/stat
cpu  5599257 116799 1924319 150675607 147630 0 51038 2454 0 0 cpu0 664385 19911 221078 19009148 14812 0 9832 2238 0 0 cpu1 783128 16478 282310 18416428 14325 0 6287 27 0 0 cpu2 822527 15344 275820 18355637 11215 0 5762 26 0 0 cpu3 807309 15631 277152 18399668 9697 0 7623 27 0 0 cpu5 712191 13680 245495 …
=> /proc/stat: render physical cpu number in non-view mode

src/bindings.h, src/lxcfs.c
This fixes SEGV in `lxcfs_release/releasedir` when path=NULL. 
Avoid the use of paths doing the release and prefer to inspect the type `file_info` struct.
Print an error in the case no valid type can be detected.
=> lxcfs: handle NULL path in lxcfs_releasedir/lxcfs_release

tools/meson-render-jinja2.py
Otherwise /usr/share/lxc/config/common.conf.d/00-lxcfs.conf loses its trailing newline
=> build: tools: keep trailing newline in jinja2 renderer

.github/workflows/commits.yml, .github/workflows/tests.yml, tests/test_cgroup.in, tests/test_meminfo_hierarchy.sh.in, tests/test_proc.in, tests/test_sigusr2.sh.in
We've moved snap from core20 to core22, let's test LXCFS on Ubuntu 22.04 too.
=> github: start using ubuntu-22.04 image

src/proc_cpuview.c, src/proc_cpuview.h, src/proc_fuse.c, src/sysfs_fuse.c
lxcfs use cpuset cgroup path to get cpu cgroup cfs_quota, cfs_period info, it works in most usecase.
however, if we deploy lxcfs on kubernetes with containerd runtime, the cpu and cpuset cgroup path is different.
the cpuset cgroup path  use prefix "/kubepods-pod"  while the cpu cgroup path use  prefix "/system.slice/containerd.service/kubepods-" .
in this case, the "/proc/cpuinfo" will be incorrect.
=>  cpuset cgroup path maybe different from cpu cgroup path in kubernetes

src/bindings.c, src/bindings.h, src/lxcfs.c, src/proc_cpuview.c
Let's start handling `FUSE_INTERRUPT` request in LXCFS.
This may help in a few scenarios:
- when buggy deadlock happens (user will be able to kill processes those are in fuse IO)
- when some fuse file becomes laggy (high lock contention?). We have seen big contention on some locks when kubernetes+monitoring software were used with LXCFS
I'm trying to be conservative and not make global changes at once. Let's just discuss about approach and convert one place at first. Then we will decide if it's helpful or not.
=> Partial support for FUSE_INTERRUPT

src/proc_loadavg.c
Idea of this fix is to always take nested locks in the same order.
At the same time, we adding an extra check to insert_node() that prevents adding a new load_node with the same cgroup (->cg field) value. This is theoretically possible because we don't hold .rilock/.lock when we call insert_node().
It looks like we have this issue from the initial
implementation of loadavg virtualization and it's hardly reproducible that's why we weren't able to notice it.
Fixes: #605
=> proc_loadavg: fix ABBA deadlock between read/refresh

src/proc_fuse.c
It was found that the personality within the container was not being properly respected, which for large numbers of CPUs would break reporting of `/proc/cpuinfo` in arm32 containers running on an arm64 host.
Tested on an arm64 QEMU VM; with this fix the 32bit container now properly reports `/proc/cpuinfo`. Shamelessly copied most of the code from the existing `proc_read_with_personality()`.
Fixes: #608.
=> proc: Fix /proc/cpuinfo not respecting personality

src/proc_loadavg.c
Newer compiler like Clang 16 and GCC 14 have certain error enabled by default, namely -Werror=incompatible-function-pointer-types. Which resutls in build error such as:
```
proc_loadavg.c:606:10: error: incompatible integer to pointer conversion returning int from a function with result type pthread_t
```
My patch supresses the error for now, but a proper fix would be better. Fist discovered on Gentoo linux (bug #894348).
Bug: https://bugs.gentoo.org/894348
Closes: https://github.com/lxc/lxcfs/issues/561
=> proc_loadavg.c: Fix incompatible integer to pointer conversion

src/proc_cpuview.c
struct cg_proc_stat *cur;
...
lxcfs_debug("Removing stat node for %s\n", cur);
should be:
lxcfs_debug("Removing stat node for %s\n", cur->cg);
Only reproducible when DEBUG macro is defined.
=> cpuview: pass a correct argument to lxcfs_debug

src/lxcfs.c, src/proc_loadavg.c, src/proc_loadavg.h
Cleanup start_loadavg code:
- add a new external symbol load_daemon_v2 with the pthread_create-like signature
- make hacky casts of pthread_t to int (and reverse) unnecessary for new API users
Related to: #610
=> loadavg: make cleanup of start_loadavg

src/proc_fuse.c
The "total_cache" from memory.stat of cgroup includes the memory used by tmpfs files ("total_shmem"). Considering it as available memory is wrong because files created on a tmpfs file system cannot be simply reclaimed.
So the available memory is calculated with the sum of:
* Memory the kernel knows is free
* Memory that contained in the kernel active file LRU, that can be reclaimed if necessary
* Memory that is contained in the kernel non-active file LRU, that can be reclaimed if necessary
=> proc: fix MemAvailable in /proc/meminfo to exclude tmpfs files

config/init/systemd/lxcfs.service.in
This is probably in a postinst for a debian package or a snap somewhere, but we're repackaging it somewhere and I have an ugly sed to fix it up. Let's do it here instead.
=> systemd: mkdir -p the target mount dir

src/syscall_numbers.h
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html
=> Add macro pivot&bpf for loongarch64

share/lxc.mount.hook.in
Closes #625
Suggested-by: amateur80lvl
=> lxc.mount.hook: Skip cpu sysfs logic if missing target

src/cgroups/cgroup_utils.c
See:
https://github.com/lxc/lxcfs/pull/617#discussion_r1533524372
Suggested-by: Signed-off-by: Christian Brauner (Microsoft) <christian.brauner@ubuntu.com>
=> cgroup_utils: explicitly check for cgroup2 FDs in cgroup_walkup_to_root

src/proc_fuse.c, src/utils.c, src/utils.h
---
(partially) closes #636 (re-submission of #637).
=> proc: checks system security policy before trying to get personalities

meson.build, src/bindings.c, src/bindings.h, src/lxcfs.c, tests/main.sh.in
It's just an updated version of https://github.com/lxc/lxcfs/pull/621
Unfortunately, I wasn't able to update the original branch for some reason GitHub just automatically closed a PR after I force-pushed my edits into the original PR branch.
=> Allow overriding RUNTIME_DIR with a cli flag #2

.github/workflows/tests.yml
Only after:
https://github.com/lxc/lxcfs/pull/648
https://github.com/lxc/lxcfs/pull/649
=> github: add live upgrade test between stable-{5,6} branches

tests/live-upgrade-test.sh.in
--enable-cgroup has appeared in 6.0
=> tests: live-upgrade test remove --enable-cgroup (stable-5.0)

src/lxcfs.c
We used the macros that were implemented for lxcfs_release() to fix the NULL path issue. This will replace the existing strcmp solution. 
These macros have already been merged into the main branch to resolve the lxcfs_release() issue. 
fix #635
=> Fix lxcfs read null

src/lxcfs.c, tests/test_proc.in
After #640 was merged we've got the entire
procfs subtree unavailable.
procfs can not be converted `LXCFS_TYPE_PROC` check in `readdir` because we don't have a designated `enum lxcfs_virt_t`-typed value for procfs directory. We can not introduce it too as it will break live upgrades of liblxcfs.
Fixes: #640
=> lxcfs: fix readdir for procfs subtree

src/cgroups/cgfsng.c, src/cgroups/cgroup_utils.h
When LXCFS daemon runs in a root cgroup of cgroup2 tree, we need to go down the tree when checking for memory.swap.current.
We already have some logic to go up the tree from LXCFS daemon's cgroup, but it's useless when LXCFS daemon sits in the cgroup2 tree root.
=> cgroups/cgfsng: improve swap accounting support detection

src/proc_loadavg.c
This resolves the issue with reload described in https://github.com/lxc/lxcfs/issues/678
=> proc_loadavg: Prevent integer overflow calculating the sleep interval
